import { SIGNUP_FORM_FIELD_KEY } from './frame/signup-form';

export const SIGNUP_FIELD_NAME = {
  LOGIN: 'login',
  PASSWORD: 'password',
};

export const SIGNUP_FORM_FIELD_NAME = {
  [SIGNUP_FORM_FIELD_KEY.LOGIN]: SIGNUP_FIELD_NAME.LOGIN,
  [SIGNUP_FORM_FIELD_KEY.PASSWORD]: SIGNUP_FIELD_NAME.PASSWORD,
};

export const SIGNUP_ACTION_TYPE = {
  SIGNUP_UPLOAD_FORM_PANDING: 'SIGNUP_ACTION_TYPE.AUTH_UPLOAD_FORM_PANDING',
  SIGNUP_UPLOAD_FORM_SUCCESS: 'SIGNUP_ACTION_TYPE.AUTH_UPLOAD_FORM_SUCCESS',
  SIGNUP_UPLOAD_FORM_ERROR: 'SIGNUP_ACTION_TYPE.AUTH_UPLOAD_FORM_ERROR',
  SIGNUP_UPLOAD_FORM_RESET: 'SIGNUP_ACTION_TYPE.AUTH_UPLOAD_FORM_RESET',
};
